on:
  pull_request:

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "test2" > test.txt

      - id: vars
        run: echo "::set-output name=branch::${GITHUB_HEAD_REF##*/}"

      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.vars.outputs.branch }}-${{ github.run_id }}

      - uses: EndBug/add-and-commit@v7
        with:
          message: 'chore: approve visual changes'
          new_branch: ${{ steps.vars.outputs.branch }}-${{ github.run_id }}

      - uses: LouisBrunner/checks-action@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test
          action_url: '-'
          conclusion: action_required
          output: |
            {"summary": "Approve", "actions": [{"label": "Approve Changes", "description": "Approve", "identifier": "commit-changes"}]}
